# Site settings for Python Game Tutorial
title: Spellcode - Python Game Tutorial for Kids
description: A fun and interactive tutorial to teach Python programming to children through game development
baseurl: "/Spellcode" # the subpath of your site
url: "https://rotzlucky.github.io" # the base hostname & protocol for your site

# SEO and metadata
author: SpellCode Team
email: contact@spellcode.dev
lang: en # Default site language
timezone: UTC

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'

# Performance optimizations
incremental: false # Disable for development to avoid issues
strict_front_matter: false # Relax validation for development
liquid:
  error_mode: warn # Warn instead of erroring
  strict_filters: false
  strict_variables: false

# theme: minima  # Removed to avoid conflicts with custom CSS

# Multilingual settings
languages:
  - code: en
    name: English
    flag: 🇬🇧
    default: true
    locale: en_US
  - code: de
    name: Deutsch
    flag: 🇩🇪
    locale: de_DE

# Collections configuration
collections:
  lessons:
    output: true
    sort_by: order
    permalink: /:collection/:path/

# Default front matter with language-aware settings
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: en # Default language for all pages
  - scope:
      path: ""
      type: "lessons"
    values:
      layout: lesson
      lang: en # Default lesson language
  - scope:
      path: "_lessons"
      type: "lessons"
    values:
      layout: lesson
  # German lesson defaults
  - scope:
      path: "_lessons"
      type: "lessons"
    values:
      layout: lesson
    where:
      lang: de

# GitHub Pages compatible plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag # Enhanced SEO metadata
  - jekyll-redirect-from # Better redirect handling

# Plugin configurations
feed:
  posts_limit: 10
  excerpt_only: true

# SEO tag configuration
seo:
  type: WebSite
  name: Spellcode - Python Game Tutorial for Kids
  links:
    - https://rotzlucky.github.io/Spellcode

# Enhanced exclusions for cleaner builds
exclude:
  # Development files
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - Dockerfile
  - README.md
  - .dockerignore
  - vendor/
  - .idea/
  - .vscode/
  - .git/
  - .gitignore
  
  # Build artifacts
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - "*.log"
  
  # Backup and temporary files
  - lessons_backup/
  - "*.bak"
  - "*.tmp"
  - "*~"
  
  # OS generated files
  - .DS_Store
  - Thumbs.db

# Development settings (commented out for production)
# livereload: true
# incremental: true
# profile: true

# Compression and optimization
sass:
  style: compressed
  sourcemap: never

# Markdown processing
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# File processing
keep_files:
  - assets/images
  - assets/css
  - assets/js

# Timezone and locale
timezone: Europe/Berlin # Adjust based on your primary audience
