# Site settings for Python Game Tutorial
title: Spellcode - Python Game Tutorial for Kids
description: A fun and interactive tutorial to teach Python programming to children through game development
baseurl: "/Spellcode" # the subpath of your site
url: "https://rotzlucky.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# theme: minima  # Removed to avoid conflicts with custom CSS

# Multilingual settings
languages:
  - code: en
    name: English
    flag: 🇬🇧
    default: true
  - code: de
    name: Deutsch
    flag: 🇩🇪

# Collections
collections:
  lessons:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "lessons"
    values:
      layout: lesson

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude development files
exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - Dockerfile
  - README.md
  - .dockerignore
  - vendor/
  - .idea/
